version: '2'
services:
  jenkins:
    image: zenijenkins
    container_name: zenijenkins
    user: jenkins
    privileged: true
    volumes:
    - home/docker/volume:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/libltdl.so.7
    ports:
      - "8180:8080"
      - "5000:5000"
      - "50000:50000"
